### ISSUE TITLE
Blank Window after login

### ISSUE THREAD

**Issue by wundersolutions-juanjo** [passbolt/passbolt-windows#11]
Hi, apologies for the lack of info, but as of now I haven't been able to really get anything else

After a successful login on the windows application (Having previously imported the account-kit.passbolt file), following the loading animations, the window changes into a blank view, with nothing to do other than managing the window itself (resizing, moving, etc)

An erroneous password "fails successfully"
PASSBOLT_PLUGINS_DESKTOP_ENABLED variable is set to true
HTTPS is being used with a valid certificate (Running behind a caddy reverse proxy)
The chrome extension is working fine

Im assuming opening the devtools (since it seems like an edge webview) would allow me to just solve the issue myself, but I haven't been able to do so (I assume the release version won't allow it?)

**Comment by scadra** [comment]
@wundersolutions-juanjo ,

Sorry for this issue, devtools are not allow on production and it is a security feature that we are applying.

So if I summarise the import success and you are not able to access you workspace. Can you provide me this informations : - Which version are you using ? 
- Are you using the windows store, msixbundle from github, or sideloading ?
- Which API version are you using ?
- Are you using MFA and it is working ? (DUO is not supported on the windows app)

Thanks in advance

**Comment by scadra** [comment]
A ticket PB-35131 has been created to track this topic

**Comment by wundersolutions-juanjo** [comment]
Hi @scadra 

I think i'm using the Store Version, although I installed it with an .exe installer. The installer version is 22408.0807.01.0.
Im not entirely sure on the API version. The webpage reports that the server is on 4.9.1
I'm not using MFA at all

**Comment by scadra** [comment]
@wundersolutions-juanjo ,

We are not providing .exe installer so I think you are using the Store version. 
Can you confirm the windows app version. On the footer you can find the heart and you should see the version.

Are you using a virtual machine ?

**Comment by wundersolutions-juanjo** [comment]
Right, the .exe was downloaded from the MS store (https://apps.microsoft.com/detail/9pfxs2wvkvpb)
I'm using Client 1.3.1
I'm not using a virtual machine, although WSL is currently installed

**Comment by wundersolutions-juanjo** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'groups_users')
    at AllowIfGroupManagerInOneGroupFunction.execute (allowIfGroupManagerInOneGroupFunction.js:24:17)
    at CanUse.getByRbacOrDefault (canUseService.js:55:34)
    at CanUse.canRoleUseUiAction (canUseService.js:30:19)
    at RbacContextProvider.canIUseUiAction (RbacContext.js:51:19)
    at DisplayMainMenu.render (DisplayMainMenu.js:81:58)
    at finishClassComponent (react-dom.development.js:17485:1)
    at updateClassComponent (react-dom.development.js:17435:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)

It appears `getByRbacOrDefault(rbac, actionName, user)` is being called without the `user` argument (canUseService.js:30`) which leads to the typeError at AllowIfGroupManagerInOneGroupFunction
    
 Current href are https://[hash].[domain]/app/passwords (DevTools `/rendered/index-workspace.html`) and `/Background/index-workspace.html`

**Comment by scadra** [comment]
Thanks for this I will add it to ticket to deploy the fix on the next ticket

**Comment by scadra** [comment]
@wundersolutions-juanjo a fix has been deployed with the new release 1.4.0

**Comment by wundersolutions-juanjo** [comment]
Confirmed working, thank you very much!
