### ISSUE TITLE
PB-36601 cant change password in windows app with passbolt cloud

### ISSUE THREAD

**Issue by support-tt** [passbolt/passbolt-windows#13]
We test passbolt at the moment with the cloud option. We changed the password(passphrase) for one of our accounts.
After a relogin in the browser extention and on the website the account was working there fine.

All with the newest version.

In the Windows app we cant change the password with the error 
`passbolt_browser_extension_src_all_background_page_service_session_storage_passphraseStorageService__WEBPACK_IMPORTED_MODULE_1__.default.isSessionKeptUntilLogOut is not a function
`
reboot of the client doesnt help.  Even a reinstall of the app doesnt help because the account is kept.

How we fix this and i think this should work without any issues.

Greetings :)

**Comment by support-tt** [comment]
ok after removing the credentials from the windows credential manager it works again. Is that a planed behaviour ?

**Comment by scadra** [comment]
@support-tt,

A ticket has been created PB-36601. We will take care of this issue as soon as possible

**Comment by scadra** [comment]
@support-tt a fix has been deployed with the new release 1.4.0
