### ISSUE TITLE
Difficulty Compiling passbolt-windows: Missing passbolt.csproj and passbolt.exe

### ISSUE THREAD

**Issue by joseraeiro** [passbolt/passbolt-windows#2]
Hello Passbolt Team,

I am encountering significant issues with compiling the passbolt-windows project, primarily due to the absence of passbolt.exe and now the missing passbolt.csproj file. These challenges led me to attempt opening passbolt.sln, where I discovered the missing project file issue.

Detailed Problem Context

Initial Issue with passbolt-windows:

When attempting to compile the passbolt-windows project, I encountered errors related to the absence of passbolt.exe.
This file was expected to be in the directory C:\Users\jraeiro\Source\Repos\passbolt-windows\passbolt\bin\x64\Debug, but it was not being generated, leading to compilation failures.

Attempting to Resolve via passbolt.sln:

In an effort to troubleshoot the above issue, I opened passbolt.sln to inspect the solution and project configuration.
This is when I encountered the error regarding the missing passbolt.csproj file.
Error Message:
```
The project file could not be loaded. Could not find file 'C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\passbolt.csproj'.
```

The file is not present in the specified directory, and I have been unable to locate it elsewhere in the repository.

Steps Taken

Searched the entire local repository for the passbolt.csproj file.
Checked recent commits for any changes to the file's location or existence.
Re-cloned the repository to confirm if the file is absent in the source.
Attempted various build configurations and platforms to resolve the passbolt.exe missing issue.

Request for Assistance

Could you assist me with the following queries?

- Is the passbolt.csproj file located elsewhere, or has it been renamed in the repository?
- How can I address the issue of passbolt.exe not being generated during the build process?
- Any recommended steps or guidelines for setting up and successfully compiling the passbolt-windows project would be highly valuable.

I am keen to contribute to Passbolt and would greatly appreciate any guidance or help in resolving these issues.

Thank you for your support.

Best regards,

**Comment by Gamabunta57** [comment]
Hello @joseraeiro!

Thanks for your report.

I took a look at the repo, the `passbolt.sln` should have been removed actually. It's something we missed to do.
The right solution file is `passbolt-windows.sln`, the former one is from an older version that we don't have anymore. 
We will remove the file in a next release to avoid the confusion 🙏

**Comment by joseraeiro** [comment]
Hello @Gamabunta57!

Thank you for your kind explanation.

Thing is, like I had stated earlier, I was drawn into `passbolt.sln` because I was receiving the following error while compiling passbolt-windows.sln:

```
Build started...
Restored C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\passbolt-windows.csproj (in 1.88 sec).
Restored C:\Users\jraeiro\source\repos\passbolt-windows\passbolt-windows-tests\passbolt-windows-tests.csproj (in 1.88 sec).
1>------ Build started: Project: passbolt-windows, Configuration: Debug x64 ------
1>C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\Utils\SerializationHelper.cs(69,37,69,56): error CS0246: The type or namespace name 'SerializationBinder' could not be found (are you missing a using directive or an assembly reference?)
2>------ Build started: Project: passbolt-windows-tests, Configuration: Debug x64 ------
2>C:\Users\jraeiro\source\repos\passbolt-windows\passbolt-windows-tests\passbolt-windows-tests.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\bin\x64\Debug\passbolt.exe'
2>CSC : error CS0006: Metadata file 'C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\bin\x64\Debug\passbolt.exe' could not be found
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 4:06 PM and took 17.061 seconds ==========
```

As for Error List window, it has the following information:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot resolve Assembly or Windows Metadata file 'C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\bin\x64\Debug\passbolt.exe'	passbolt-windows-tests	C:\Users\jraeiro\source\repos\passbolt-windows\passbolt-windows-tests\passbolt-windows-tests.csproj		
Error	CS0006	Metadata file 'C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\bin\x64\Debug\passbolt.exe' could not be found	passbolt-windows-tests	C:\Users\jraeiro\source\repos\passbolt-windows\passbolt-windows-tests\CSC	1	Active
Error	CS0246	The type or namespace name 'SerializationBinder' could not be found (are you missing a using directive or an assembly reference?)	passbolt-windows	C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\Utils\SerializationHelper.cs	69	Active
```

Can you help?

**Comment by joseraeiro** [comment]
Good news! I was able to successfully compile the code, although with some warnings:

```
1>------ Build started: Project: passbolt-windows, Configuration: Debug x64 ------
1>C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\obj\x64\Debug\MainPage.g.i.cs(20,61,20,71): warning CS0108: 'MainPage.Background' hides inherited member 'Control.Background'. Use the new keyword if hiding was intended.
1>C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\MainPage.xaml.cs(46,13,46,73): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
1>C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\Utils\SerializationHelper.cs(43,17,43,23): warning CS0618: 'JsonSerializerSettings.Binder' is obsolete: 'Binder is obsolete. Use SerializationBinder instead.'
1>C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\Controllers\MainController.cs(198,17,198,72): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
1>C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\Services\NavigationService\BackgroundNavigationService.cs(24,24,24,37): warning CS0169: The field 'BackgroundNavigationService.trustedDomain' is never used
1>C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\Services\NavigationService\BackgroundNavigationService.cs(23,40,23,47): warning CS0414: The field 'BackgroundNavigationService.mfaUrls' is assigned but its value is never used
1>  passbolt-windows -> C:\Users\jraeiro\source\repos\passbolt-windows\passbolt\bin\x64\Debug\passbolt.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 5:25 PM and took 21.256 seconds ==========
```

I had to make a minor change to SerializationHelper.cs and to delete the passbolt-windows-tests part of the project.

The issue with my code seemed to be related to the SerializationBinder class, which was likely not being recognized in my SingleTypeBinder class definition. To fix this, I've included the correct namespace for SerializationBinder. 

Add Using Directive for System.Runtime.Serialization:

Since SerializationBinder is typically part of the System.Runtime.Serialization namespace, I've added the using directive at the top of my file.

```
using System.Runtime.Serialization;
```

I updated the SingleTypeBinder Class:

I made sure that my SingleTypeBinder class inherited from SerializationBinder correctly.

Here's how my SingleTypeBinder class looks like:

```
public class SingleTypeBinder : SerializationBinder
{
    private readonly Type _type;

    public SingleTypeBinder(Type type)
    {
        _type = type;
    }

    public override Type BindToType(string assemblyName, string typeName)
    {
        if (typeName != _type.FullName)
            throw new JsonSerializationException($"Deserialization of type {typeName} is not allowed.");

        return _type;
    }
}

```

**Comment by Gamabunta57** [comment]
I took a look. So, actually the not found `SerializationBinder` type comes from a NuGet package `NewtonSoft.Json`. Did you downloaded the referenced packages already?

If not you can try to restore the NuGet packages like described here 
https://learn.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-visual-studio

Then your VS should be able to resolve the missing dependencies and build the app.

**Comment by Gamabunta57** [comment]
Ha sorry @joseraeiro for my response that might seemed a bit not to the point, my page wasn't refreshed for some reason and I didn't see your answer.
Yes, you identified the origin of the problem. Later on if you want to go on with the original source you could still try to refresh the NuGet package as mentioned if you wish.

Glad, you could solve your issue, and I hope you'll enjoy this desktop app.
