### ISSUE TITLE
Windows Desktop App - Account Creation PGP Key Import Issue

### ISSUE THREAD

**Issue by joseraeiro** [passbolt/passbolt-windows#4]
Hello Passbolt community!

### Description:
I am encountering an issue during the account creation process with the Passbolt Windows desktop application (Beta version). When prompted to import my PGP private key, the application does not accept neither my `.txt` file nor my `.key` file. I have ensured that the key is correctly formatted and saved with UTF-8 encoding, but the application repeatedly fails to import it.

### Steps to Reproduce:
1. Open the Passbolt Windows desktop application.
2. Proceed to the account creation step.
3. When prompted, attempt to import the PGP private key using the 'Select a file' option.

### Expected Behavior:
The application should accept the PGP private key and proceed with the account creation.

### Actual Behavior:
The application does not import the PGP private key, preventing the completion of the account setup.

### Additional Information:
- The key file includes the correct 'BEGIN' and 'END' PGP key block headers.
- There are no extra spaces or line breaks in the key file.
- The file is saved with a `.key` extension.

Considering this is an early version, I am unsure if this behavior is a known issue or if there are additional steps I can take to troubleshoot further.

Any assistance or insight into this issue would be greatly appreciated.

**Comment by Gamabunta57** [comment]
Hey :wave: @joseraeiro!

So, for that part we do the thing a bit differently than the browser extension. On the browser extension when you do an account recover we only asks for the private key.

On the desktop app, we have a more complete kit to provide (it includes things such as Passbolt instance URL, the security token, the Passbolt public server key etc).

This file is actually a `.passbolt` file that is a base64 of a json content (with all the elements detailed earlier) and signed with the user's private key. The Desktop app requires that file (btw, if you want to take a look a the risk analysis we have: https://docs.google.com/document/d/1kkDuuztv1l9syc8U7xFmif3hBFlRdlXweQfyIZVdZBE)

For the procedure about how to get this file for your user profile, you go there: [Passbolt community forum](https://community.passbolt.com/t/windows-application-developer-edition-v0-5-0/8906)

**Comment by joseraeiro** [comment]
I see and I'm now able to create the account. 

Although now the application is crashing after having loaded my kit.

Thank you very much for your kind guidance, I shall open another issue.
