### ISSUE TITLE
Password Folder Management

### ISSUE THREAD

**Issue by BizkitX** [passbolt/passbolt-windows#6]
Currently trying out the desktop app and noticed that once a password is created, we are unable to move it to a different folder. This is possible in the web ui with drag and drop.

Thanks

**Comment by scadra** [comment]
Hey @BizkitX,

It is a bug known of Webview2, the good new is : we have found a work around to support the drag and drop in the incoming version 1.1.0

**Comment by scadra** [comment]
Hey @BizkitX 

I hope the bug is gone, can you confirm it ?

Thanks in advance

**Comment by BizkitX** [comment]
Hey @scadra,

Just tested and is appears to be working correctly.

Many thanks!

**Comment by scadra** [comment]
"
