### ISSUE TITLE
passbolt-windows-tests

### ISSUE THREAD

**Issue by nunda-tiobe** [passbolt/passbolt-windows#7]
Hi, 

I'm trying to run the tests but I run into some issue's.
Are there files missing from this repo?

 ParseAppUrlServiceTests.cs

Line 44
`
        public void ShouldParse(string scenario, string url, string domain)
        {
            try
            {
                ParseAppUrlService.Parse(domain, url);
            }
            catch (Exception ex)
            {
                Assert.Fail($"Should parse: {scenario} for {url}. Error: {ex.Message}");
            }
        }
`
ParseAppUrlService does not exist.

**Comment by scadra** [comment]
hey @nunda-tiobe , 

Actually the test project is not supported maintain anymore. We are discussing about a different approach for the future.

Thanks for it
